x = SCREEN_WIDTH / 2;
y = SCREEN_HEIGHT + sprite_get_height(spr_gustavo_intro);
movespeed = 8;
state = states.transitioncutscene;
depth = -600;
sprite_index = spr_tvstatic;
image_index = 0;
image_speed = 0.35;
spr = noone;
obj_camera.lock = true;
fmod_event_one_shot("event:/sfx/ui/tvswitch");
shakey = 0;
