hsp = 0;
vsp = 0;
hsp_carry = 0;
vsp_carry = 0;
platformid = noone;
grav = 0.5;
spd = 18;
playerid = noone;
snd = fmod_event_create_instance("event:/sfx/noise/skatealone");
fmod_event_instance_play(snd);
